---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/occ.qodit.org
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/find $DEPLOYPATH -path $DEPLOYPATH/.git -prune -o -type d -exec /bin/chmod 755 {} +
    - /bin/find $DEPLOYPATH -path $DEPLOYPATH/.git -prune -o -type f -exec /bin/chmod 644 {} +
